### ISSUE TITLE
virt-install --cloud-init: add support for network-config

### ISSUE THREAD

**Issue by dseomn** [virt-manager/virt-manager#294]
**Distro**: Debian GNU/Linux 11 (bullseye)

From https://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html
> Network configuration can also be provided to cloud-init in either Networking Config Version 1 or Networking Config Version 2 by providing that yaml formatted data in a file named `network-config`.

Would it be possible to add a new sub option to `virt-install --cloud-init` for the `network-config` file, similar to the existing `user-data` and `meta-data` options? Or maybe a generic way to add files to the ISO image?

**Comment by sej7278** [comment]
thanks @dseomn but really i meant virt-install examples, i tried something like this and it was just ignored by ubuntu:

```
virt-install --cloud-init user-data="#cloud-config
users:
  - default
  - name: foobar
    gecos: Foo B. Bar
    primary_group: foobar
    groups: users
    selinux_user: staff_u"
```
