### ISSUE TITLE
consider cloud.cfg for ssh user (with --cloud-init)

### ISSUE THREAD

**Issue by fkooman** [virt-manager/virt-manager#307]
Currently when using --cloud-init the SSH key is configured for the root user. Other cloud-init based systems would use `/etc/cloud/cloud.cfg` (distro specific) to configure a user, e.g. on Fedora this would be the user `fedora`, on CentOS it is user `centos` and on Debian it is user `debian`. 

See e.g. the snippet in `/etc/cloud/cloud.cfg` on Fedora:

```
# System and/or distro specific settings
# (not accessible to handlers/transforms)
system_info:
   # This will affect which distro class gets used
   distro: fedora
   # Default user name + that default users groups (if added/used)
   default_user:
     name: fedora
     lock_passwd: True
     gecos: fedora Cloud User
     groups: [wheel, adm, systemd-journal]
     sudo: ["ALL=(ALL) NOPASSWD:ALL"]
     shell: /bin/bash
   # Other config here will be given to the distro class and/or path classes
   paths:
      cloud_dir: /var/lib/cloud/
      templates_dir: /etc/cloud/templates/
   ssh_svcname: sshd
```

The (big) advantage is that the root user can remain disabled.
