### ISSUE TITLE
[RFE]

### ISSUE THREAD

**Issue by andreabolognani** [virt-manager/virt-manager#882]
Today, my workflow for creating VMs from Fedora cloud images involves the creation of a `user-data.yaml` file containing

```yaml
#cloud-config

password: linux
chpasswd:
  expire: false

runcmd:
  - touch /etc/cloud/cloud-init.disabled
```

and passing it to virt-install via `--cloud-init user-data=user-data.yaml`. This works fine, but is a bit unwieldy.

After learning about this, @phrdina suggested the following:

> you can make the setup a bit easier by using `--cloud-init clouduser-ssh-key=/home/user/.ssh/id_rsa.pub` instead of creating custom user-data file, but it would require ssh into the VM instead of using console .... I wonder if we should add `clouduser-password-file` and `clouduser-password-generate` like we have for root

That sounds like a fantastic idea to me! Especially since it would compose with the existing `--cloud-init disable=on`, thus taking care of the part that `runcmd` is there for in my `user-data.yaml`.
